server:
    port: 3000

db:
    postgres:
        type: 'postgres'
        port: '5432'
        database: 'usergroupmanagement'
        synchronize: false
    mongo:
        type: 'mongodb'
        useUnifiedTopology: true